learning_platform/courses/urls.py
from django.urls import path

from . import views


app_name = 'courses'

urlpatterns = [
    path('', views.CourseListView.as_view(), name='course_list'),
    path(
        '<slug:course_slug>/',
        views.CourseDetailView.as_view(),
        name='course_detail',
    ),
    path(
        '<slug:course_slug>/<slug:lesson_slug>/',
        views.LessonDetailView.as_view(),
        name='lesson_detail',
    ),
]

learning_platform/learn_platform/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from users import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls', namespace='courses')),
    path(
        'auth/registration/',
        views.UserCreateView.as_view(),
        name='registration',
    ),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('pages.urls', namespace='pages')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

learning_platform/pages/urls.py
from django.urls import path

from . import views


app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contacts/', views.contacts, name='contacts'),
    path('profile/', views.profile, name='profile'),
]

learning_platform/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© LingWorld</p>    
  </footer>

learning_platform/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'pages:index' %}">
          <img src="{% static 'img/earth-europe-solid.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="logo">
          LingWorld
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item dropdown">
          <a href="{% url 'courses:course_list' %}" class="nav-link">
            Курсы
          </a>
          <ul class="dropdown-menu">
            {% for course in courses %}
                <li><a class="dropdown-item" href="{{ course.get_absolute_url }}">{{ course.title }}</a></li>
            {% endfor %}
          </ul>
        </li>
        <li class="nav-item">
          <a href="{% url 'pages:contacts' %}" class="nav-link">
            Контакты
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'pages:about' %}" class="nav-link">
            О нас
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'pages:profile' %}" class="nav-link">
            Профиль
          </a>
        </li>
        {% comment %} {% if user.is_authenticated %}
          <div class="btn-group" role="group" aria-label="Basic outlined example">
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'blog:profile' user.username %}">{{ user.username }}</a></button>
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'logout' %}">Выйти</a></button>
          </div>
        {% else %}
          <div class="btn-group" role="group" aria-label="Basic outlined example">
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'login' %}">Войти</a></button>
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
              href="{% url 'registration' %}">Регистрация</a></button>
          </div>
        {% endif %} {% endcomment %}
      </ul>
    </div>
  </nav>
</header>